CREATE TABLE tasks (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(1000),
  status VARCHAR(20) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
